#!/bin/bash

request=$(curl -s "http://api.bitly.com/v3/shorten?login=nickholb&apiKey=R_c54a43916b20475b9dcdd121bf99fd6b&longUrl=$1&format=txt")
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
# outputting the result to the user to see
echo "Shortened URL: $request"
# This yanks the output to the clipboard
echo $request | pbcopy


